name: 'compute_health_check_http'

terraform:
  var:
    region: 'us-central1'
    name: 'autohealing-health-check-http'
    check_interval_sec: 5
    timeout_sec: 5
    healthy_threshold: 2
    unhealthy_threshold: 10
    request_path: '/'
    port: 80
